# Steps:
# - Checkout repo
# - Prod build of Angular App
# - Prod build of Node App
# - Connect to EC2 instance
# - Copy files
name: Yarn Workspace Prod Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Copy environment files
        run: |
          mkdir -p ./projects/public-client/src/environments
          mkdir -p ./projects/public-server/src/environments
          mkdir -p ./projects/dive-inn-lib/src/environments
          echo "Folders created"          
          touch ./projects/public-client/src/environments/environment.prod.ts
          touch ./projects/public-server/src/environments/environment.ts
          touch ./projects/dive-inn-lib/src/environments/environment.prod.ts
          echo "Files touched"
          echo "${{ secrets.ENV_FILE_PUBLIC_CLIENT }}" > ./projects/public-client/src/environments/environment.prod.ts
          echo "${{ secrets.ENV_FILE_PUBLIC_SERVER }}" > ./projects/public-server/src/environments/environment.ts
          echo "${{ secrets.ENV_FILE_DIVE_INN_LIB }}" > ./projects/dive-inn-lib/src/environments/environment.prod.ts

      - name: Build Frontend
        run: yarn build-fe_public

      - name: Build Backend
        run: yarn build-be_public_linux
##
      - name: Connect to EC2 instance and copy files
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.EC2_HOST }}:${{ secrets.EC2_PORT }}"
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_RSA }}
          script: |
            mkdir -p /var/www/html/diveinndenver.com
            scp -r ./dist/public-client/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/diveinndenver.com/public-client
            scp -r ./dist/public-server/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/diveinndenver.com/public-server
